[tool.poetry]
name = "flymy-comfyui-repo-gen"
version = "0.1.0"
description = ""
authors = ["D1-3105 <lyerhd@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
