name: Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint_tests:
    runs-on: ubuntu-latest

    container:
      image: denti/dev:py3.12-1.0.0
      credentials:
        username: ${{ secrets.REGISTRY_USER }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    steps:
      - name: Check out git repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: pip install -e .

      - name: Lint code
        run: black --preview  --check flymy_comfyui_repo_gen/


  unit_tests:
    runs-on: ubuntu-latest

    container:
      image: denti/dev:py3.12-1.0.0
      credentials:
        username: ${{ secrets.REGISTRY_USER }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    steps:
      - name: Check out git repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: pip install -e .

      - name: Run unit tests
        run: pytest flymy_comfyui_repo_gen/tests/
